@startuml
'https://plantuml.com/class-diagram


class Question {
 id: int Primary key
 title: string
 text: string
 type: labels|options
 labelForHigh?: string
 labelForLow?: string
}

class QuestionOption {
    title: string
    questionId: int
}

Question "1" - "*" QuestionOption


@enduml